### ISSUE TITLE
Support CircleCI

### ISSUE THREAD

**Issue by nilleb** [nilleb/ccguard#6]
Apparently (reference required: @volnt :-) ) CircleCI does not allow sending data to an external service during the build.
Thus we can not send data to a redis or mysql instance.

A solution could be to expose a service (flask based) receiving code coverage data. This service could also display code coverage for a commit and a diff between two commits.

Along with the service, we should publish a CircleCI orb (https://circleci.com/orbs/registry/, https://circleci.com/docs/2.0/creating-orbs/)

**Comment by nilleb** [comment]
a web adapter c1fd3348376a73958337b298635f078a7ebcbd1e

**Comment by nilleb** [comment]
thanks @volnt, you have pointed out very interesting documents.

you weren't using TravisCI? :-)

I think that codeclimate is a great collection of tools, and I would love to use it!

**Comment by volnt** [comment]
Wow you got me lost here, yes we are using Travis 😅

**Comment by nilleb** [comment]
--> https://circleci.com/gh/nilleb/ccguard
(so, I can now say that CircleCI does not prevent the container from sending data to the internet)
